/**
 * Every user-facing string, keyed by screen.
 *
 * No literal ever goes in a component: `no-literal-jsx-strings` fails the
 * build for one (architecture §11). Seeded from the design canvas by
 * `node scripts/extract-copy.mjs`, then revised here — once a screen is built
 * against a key, this file is the authority for the words, not the artboard.
 *
 * The voice rules are linted, not just documented: no exclamation marks outside
 * the confirmation, and none of the scoreboard vocabulary the manifesto rules
 * out (`copy-voice`, design manifesto §4).
 *
 * Seeded with 1024 strings across 78 screens.
 * Some are still fixture text from the artboards — names, venues, circle names.
 * Those move to `tests/fixtures` as S0-08 builds the screens that use them.
 */
export const en = {
  /** Shared across screens. Not from any one artboard. */
  common: {
    back: 'Back',
    close: 'Close',
    cancel: 'Cancel',
    done: 'Done',
    dismiss: 'Dismiss',
  },
  account: {
    account: 'Account',
    you: 'You',
    name: 'Name',
    maya: 'Maya',
    change: 'Change',
    time_zone: 'Time zone',
    melbourne_aest: 'Melbourne (AEST)',
    email: 'Email',
    maya_example_com: 'maya@example.com',
    privacy: 'Privacy',
    what_we_keep_what_friends_see: 'What we keep, what friends see',
    email_preferences: 'Email preferences',
    meetup_updates: 'Meetup updates',
    sign_out: 'Sign out',
    delete_my_account_and_data: 'Delete my account and data',
  },
  addToCalendar: {
    add_thursday_to_your_calendar: 'Add Thursday to your calendar',
    thu_17_sep_6_30_8_30: 'Thu 17 Sep, 6:30–8:30 pm · Hope St Radio',
    apple_or_device_calendar: 'Apple or device calendar',
    downloads_an_ics_file: 'Downloads an .ics file',
    google_calendar: 'Google Calendar',
    opens_google_calendar_with_the_details_filled:
      'Opens Google Calendar with the details filled in',
    nothing_is_added_to_anyones_calendar_without:
      "Nothing is added to anyone's calendar without their tap.",
    cancel: 'Cancel',
  },
  afterAttendance: {
    brand: '{brand}',
    sunday_crew_thu_17_sep: 'Sunday Crew · Thu 17 Sep',
    glad_it_happened: 'Glad it happened.',
    thats_the_first_one_sunday_crew_has:
      "That's the first one Sunday Crew has done through {brand}. The next one starts from where this left off.",
    got_another_group_that_keeps_saying_we:
      'Got another group that keeps saying “we should catch up”?',
    start_a_circle_for_them_same_link:
      "Start a circle for them. Same link into their chat, no app for them either. You'd need to sign in so the circle has an owner.",
    start_a_circle: 'Start a circle',
    maybe_later: 'Maybe later',
  },
  appLanding: {
    brand: '{brand}',
    welcome_back_priya: 'Welcome back, Priya.',
    signed_in_as_priya_example_com_your:
      'Signed in as priya@example.com. Your circles are already here.',
    sunday_crew: 'Sunday Crew',
    locked_in_thu_17_sep_youre_going: "Locked in · Thu 17 Sep · you're going",
    links_you_tap_from_the_group_chat:
      'Links you tap from the group chat will open here from now on.',
    open_sunday_crew: 'Open Sunday Crew',
    reminders_come_on_thursday_well_ask_about:
      "Reminders come on Thursday. We'll ask about notifications then, not now.",
  },
  appSheet: {
    keep_sunday_crew_on_your_phone: 'Keep Sunday Crew on your phone',
    everything_here_keeps_working_from_the_link:
      "Everything here keeps working from the link. The app adds the bits a browser can't do.",
    one_reminder_before_each_catch_up: 'One reminder before each catch-up',
    and_a_ping_only_when_a_decision: 'And a ping only when a decision needs you',
    grey_out_your_clashes: 'Grey out your clashes',
    reads_your_calendar_on_your_phone_only:
      'Reads your calendar on your phone only. Never uploaded',
    never_rejoin_again: 'Never rejoin again',
    your_place_in_every_circle_on_every: 'Your place in every circle, on every device',
    start_one_with_another_group: 'Start one with another group',
    same_link_trick_your_other_friends: 'Same link trick, your other friends',
    get_the_app: 'Get the app',
    not_now: 'Not now',
    free_no_ads_well_remember_you_said:
      "Free. No ads. We'll remember you said not now and won't ask again for a month.",
  },
  availability: {
    title: '{title} · {dates}',
    painted_of: '{painted} of {total} days',
    times_id_actually_be_up_for: "Times I'd actually be up for",
    runs_about: '{what} run about {duration}. Replies close {deadline}.',
    what_catch_up: 'Catch-ups',
    what_dinner: 'Dinners',
    what_drinks: 'Drinks',
    what_coffee: 'Coffees',
    what_activity: 'Activities',
    duration_60: 'an hour',
    duration_90: 'an hour and a half',
    duration_120: '2 hours',
    duration_180: '3 hours',
    times_in_zone: 'Times are {zone} time.',
    after_work: 'After work',
    all_evening: 'All evening',
    morning: 'Morning',
    afternoon: 'Afternoon',
    any_time_that_day: 'Any time that day',
    clear_this_day: 'Clear this day',
    any_time_on: 'Any time on {day}',
    clear_day: 'Clear {day}',
    not_this_day: 'Not this day',
    cell: '{day}, {from} to {to}',
    cell_repeated: '{label}, after the clocks go back',
    cell_crossing: '{label}, as the clocks go back',
    clocks_go_back: 'Clocks go back',
    im_easy: "I'm easy",
    count_me_in_for_whatever_works_for: 'Count me in for whatever works for most people',
    your_friends_will_only_see_a_combined:
      "Your friends will only see a combined result. They won't see your calendar or a personal schedule view.",
    send_my_times: 'Send my times',
    sending: 'Sending',
    paint_or_easy: "Paint the times you'd be up for, or turn on I'm easy.",
    none_of_these_dates_work_for_me: 'None of these dates work for me',
    finding_the_plan: 'Finding the plan',
    couldnt_load: "We couldn't load this plan just now.",
    youre_offline: "You're offline. Connect, then try again.",
    try_again: 'Try again',
    plan_changed:
      'The plan changed, so the times you had painted were for a different question. Here are the dates being asked about now.',
    replies_closed: 'Replies have closed for this one.',
    replies_closed_body: 'Nothing more is needed from you. The plan will land in the group chat.',
    back: 'Back',
    too_many_tries: 'Too many tries from here just now. Wait a few minutes, then try again.',
    couldnt_send: "Something went wrong, so your times didn't go through. Please try again.",
    reference: 'Ref {reference}',
  },
  availabilityOverlay: {
    catch_up_next_14_days: 'Catch up · next 14 days',
    '3_of_14_days': '3 of 14 days',
    times_id_actually_be_up_for: "Times I'd actually be up for",
    catch_ups_run_about_2_hours_replies:
      'Catch-ups run about 2 hours. Replies close Tue 15 Sep, 6 pm.',
    greyed_from_personal_work_read_just_now: 'Greyed from Personal, Work · read just now',
    change: 'Change',
    mon_14_sep: 'Mon 14 Sep',
    '8_10_30_pm': '8–10:30 pm',
    '5_30_pm': '5:30 pm',
    '8_pm': '8 pm',
    '10_30_pm': '10:30 pm',
    tue_15_sep: 'Tue 15 Sep',
    not_this_day: 'Not this day',
    wed_16_sep: 'Wed 16 Sep',
    '7_9_30_pm': '7–9:30 pm',
    thu_17_sep: 'Thu 17 Sep',
    '5_30_10_30_pm': '5:30–10:30 pm',
    grey_means_your_calendar_says_busy_tap:
      "Grey means your calendar says busy. Tap to paint over it if it's wrong.",
    im_easy: "I'm easy",
    count_me_in_for_whatever_works_for: 'Count me in for whatever works for most people',
    only_the_times_you_paint_are_sent:
      'Only the times you paint are sent. Your calendar never leaves this phone.',
    send_my_times: 'Send my times',
    none_of_these_dates_work_for_me: 'None of these dates work for me',
  },
  calendarDenied: {
    times_id_actually_be_up_for: "Times I'd actually be up for",
    no_calendar_access_and_thats_fine: "No calendar access, and that's fine.",
    everything_works_without_it_paint_the_times:
      "Everything works without it. Paint the times you'd be up for and send them as usual.",
    if_you_change_your_mind_you_can:
      "If you change your mind, you can allow it in Settings › {brand} › Calendars. We won't ask again.",
    choose_my_times: 'Choose my times',
  },
  calendarExplain: {
    times_id_actually_be_up_for: "Times I'd actually be up for",
    grey_out_clashes_from_your_calendar: 'Grey out clashes from your calendar?',
    your_calendar_stays_on_this_phone_we:
      "Your calendar stays on this phone. We only use it to grey out times you're already busy, while you choose when you actually want to meet.",
    reads_busy_times_for_these_14_days: 'Reads busy times for these 14 days',
    runs_on_this_phone_only: 'Runs on this phone only',
    event_names_places_or_people: 'Event names, places or people',
    never_leave_your_phone: 'Never leave your phone',
    friends_see: 'Friends see',
    only_the_times_you_choose: 'Only the times you choose',
    you_can_always_paint_over_a_greyed:
      "You can always paint over a greyed time. Calendars aren't always right.",
    choose_calendars: 'Choose calendars',
    keep_it_manual: 'Keep it manual',
  },
  calendarPick: {
    which_calendars: 'Which calendars?',
    which_calendars_should_we_check: 'Which calendars should we check?',
    only_these_will_grey_out_times_nothing: 'Only these will grey out times. Nothing is uploaded.',
    personal: 'Personal',
    icloud: 'iCloud',
    work: 'Work',
    google_priya_work_example: 'Google · priya@work.example',
    birthdays: 'Birthdays',
    all_day_marked_free_ignored_anyway: 'All-day, marked free · ignored anyway',
    footy_fixtures: 'Footy fixtures',
    subscribed: 'Subscribed',
    use_these: 'Use these',
  },
  cancelPlan: {
    back: 'Back',
    cancel_thursdays_catch_up: "Cancel Thursday's catch-up?",
    everyone_will_see_its_off_the_circles:
      "Everyone will see it's off. The circle's record isn't changed, and you can plan another any time.",
    a_short_note_optional: 'A short note, optional',
    work_thing_came_up_sorry_all_will: 'Work thing came up, sorry all. Will try again in October.',
    well_give_you_a_message_to_paste: "We'll give you a message to paste into the group chat.",
    cancel_the_catch_up: 'Cancel the catch-up',
    keep_it: 'Keep it',
  },
  cancelledGuest: {
    sunday_crew: 'Sunday Crew',
    brand: '{brand}',
    not_going_ahead: 'Not going ahead',
    thursdays_catch_up_is_off: "Thursday's catch-up is off.",
    maya_cancelled_it_nothing_you_sent_has:
      "Maya cancelled it. Nothing you sent has been shared, and the circle's record isn't affected.",
    mayas_note: "Maya's note",
    work_thing_came_up_sorry_all_will:
      '“Work thing came up, sorry all. Will try again in October.”',
    back_to_sunday_crew: 'Back to Sunday Crew',
  },
  cancelledOrg: {
    sunday_crew: 'Sunday Crew',
    not_going_ahead: 'Not going ahead',
    thursdays_catch_up_is_off: "Thursday's catch-up is off.",
    cancelled_by_you_tue_15_sep_the:
      "Cancelled by you, Tue 15 Sep. The circle's last-caught-up date is unchanged.",
    ready_to_paste_into_the_group_chat: 'Ready to paste into the group chat',
    update_thursdays_sunday_crew_catch_up_is:
      "Update: Thursday's Sunday Crew catch-up is off. Sorry all, will try again in October. {domain}/p/8k2v",
    share_to_group_chat: 'Share to group chat',
    plan_another: 'Plan another',
  },
  candidates: {
    catch_up_next_14_days: 'Catch up · next 14 days',
    '5_of_6_replied': '5 of 6 replied',
    closes_tue_6_pm: 'Closes Tue 6 pm',
    thursday_looks_good_for_five_of_you: 'Thursday looks good for five of you.',
    alex_hasnt_answered_yet_you_can_lock:
      "Alex hasn't answered yet. You can lock a time in now or wait until Tuesday.",
    best_attendance: 'Best attendance',
    '5_of_6': '5 of 6',
    thu_17_sep: 'Thu 17 Sep',
    '6_30_8_30_pm': '6:30–8:30 pm',
    alex_hasnt_answered: "Alex hasn't answered",
    one_fewer_weekend: 'One fewer, weekend',
    '4_of_6': '4 of 6',
    sat_19_sep: 'Sat 19 Sep',
    doesnt_work_for_priya: "Doesn't work for Priya",
    also_four_a_day_later: 'Also four, a day later',
    sun_20_sep: 'Sun 20 Sep',
    '4_6_pm': '4–6 pm',
    doesnt_work_for_tom: "Doesn't work for Tom",
    review_thursday: 'Review Thursday',
    nudge_alex: 'Nudge Alex',
  },
  candidatesMember: {
    catch_up_next_14_days: 'Catch up · next 14 days',
    '5_of_6_replied': '5 of 6 replied',
    closes_tue_6_pm: 'Closes Tue 6 pm',
    thursday_looks_good_for_five_of_you: 'Thursday looks good for five of you.',
    maya_will_pick_one_of_these_once:
      'Maya will pick one of these once replies close. You can change your times until then.',
    best_attendance: 'Best attendance',
    '5_of_6': '5 of 6',
    thu_17_sep: 'Thu 17 Sep',
    '6_30_8_30_pm': '6:30–8:30 pm',
    alex_hasnt_answered: "Alex hasn't answered",
    one_fewer_weekend: 'One fewer, weekend',
    '4_of_6': '4 of 6',
    sat_19_sep: 'Sat 19 Sep',
    doesnt_work_for_priya: "Doesn't work for Priya",
    also_four_a_day_later: 'Also four, a day later',
    sun_20_sep: 'Sun 20 Sep',
    '4_6_pm': '4–6 pm',
    doesnt_work_for_tom: "Doesn't work for Tom",
    change_my_times: 'Change my times',
  },
  changeTime: {
    back: 'Back',
    ask_for_new_times: 'Ask for new times?',
    thursday_will_be_marked_as_no_longer:
      'Thursday will be marked as no longer happening and everyone will be asked again for a new window. Your place and note are kept.',
    new_window: 'New window',
    next_7_days: 'Next 7 days',
    next_14_days: 'Next 14 days',
    custom: 'Custom',
    everyone_will_see_thursday_is_off_and:
      "Everyone will see Thursday is off and get a fresh ask. Nobody's earlier times are reused without asking.",
    ask_again: 'Ask again',
    keep_thursday: 'Keep Thursday',
  },
  checkEmail: {
    check_your_email: 'Check your email.',
    we_sent_a_link_to:
      'We sent a link to {address}. Tap it to turn on updates for this meetup. The link works for 24 hours.',
    we_sent_you_a_link:
      'We sent you a link. Tap it to turn on updates for this meetup. The link works for 24 hours.',
    your_times_are_already_in_nothing_here:
      'Your times are already in. Nothing here holds up the plan.',
    wrong_address: 'Wrong address?',
    use_a_different_one: 'Use a different one',
    resend_the_link: 'Resend the link',
    resending: 'Sending another',
    resent: "We've asked for another link. It can take a few minutes to arrive.",
    too_many_tries: "That's as many links as we send to one address in a day. Try again tomorrow.",
    youre_offline: "You're offline. Connect, then try again.",
    couldnt_send: "Something went wrong, so the link didn't go. Please try again.",
    reference: 'Ref {reference}',
    back_to_circle: 'Back to {circle}',
  },
  chooseMode: {
    sunday_crew: 'Sunday Crew',
    how_do_you_want_to_start: 'How do you want to start?',
    plan_openly: 'Plan openly',
    you_set_the_window_everyone_marks_the:
      "You set the window, everyone marks the times they'd be up for, you pick the best one. Your name is on it.",
    see_if_people_are_keen: 'See if people are keen',
    ask_quietly_first_if_three_people_are:
      'Ask quietly first. If three people are keen, it opens up to find a time. If not, it closes and nobody knows you asked.',
    either_way_friends_answer_from_a_link: 'Either way, friends answer from a link. No app needed.',
  },
  circleHome: {
    sunday_crew: 'Sunday Crew',
    '6_members_about_monthly': '6 members · about monthly',
    finding_a_time: 'Finding a time',
    replies_close_tue_6_pm: 'Replies close Tue 6 pm',
    catch_up_in_the_next_14_days: 'Catch up in the next 14 days',
    '5_of_6_replied': '5 of 6 replied',
    see_how_its_looking: "See how it's looking",
    last_caught_up: 'Last caught up',
    sat_8_aug: 'Sat 8 Aug',
    next_one: 'Next one',
    no_rush: 'No rush',
    you_aim_for_about_monthly_early_october:
      'You aim for about monthly. Early October would keep the rhythm.',
    '6_members': '6 members',
    invite_link: 'Invite link',
    plan_a_catch_up: 'Plan a catch-up',
  },
  circleHomeConfirmed: {
    sunday_crew: 'Sunday Crew',
    '6_members_about_monthly': '6 members · about monthly',
    locked_in: 'Locked in',
    '5_going_1_to_confirm': '5 going · 1 to confirm',
    thu_17_sep: 'Thu 17 Sep',
    '6_30_8_30_pm_hope_st': '6:30–8:30 pm · Hope St Radio',
    details: 'Details',
    share: 'Share',
    last_caught_up: 'Last caught up',
    sat_8_aug: 'Sat 8 Aug',
    next_one: 'Next one',
    '6_members': '6 members',
    invite_link: 'Invite link',
    plan_another: 'Plan another',
  },
  circleHomeDue: {
    sunday_crew: 'Sunday Crew',
    '6_members_about_monthly': '6 members · about monthly',
    about_time_for_the_next_one: 'About time for the next one',
    its_been_about_a_month_since_sunday:
      "It's been about a month since Sunday Crew last got together. It's Tom's turn to plan, if the group's keen. No rush.",
    snooze_a_month: 'Snooze a month',
    turn_off_nudges: 'Turn off nudges',
    last_caught_up: 'Last caught up',
    thu_17_sep: 'Thu 17 Sep',
    next_one: 'Next one',
    nothing_yet: 'Nothing yet',
    '6_members': '6 members',
    invite_link: 'Invite link',
    plan_another: 'Plan another',
  },
  circleHomeJoining: {
    sunday_crew: 'Sunday Crew',
    '3_in_so_far_about_monthly': '3 in so far · about monthly',
    priya_and_tom_just_joined: 'Priya and Tom just joined',
    share_again: 'Share again',
    ready_when_you_are: 'Ready when you are',
    you_dont_have_to_wait_for_everyone:
      "You don't have to wait for everyone. Start a catch-up now and anyone who joins later can still add their times.",
    last_caught_up: 'Last caught up',
    not_yet: 'Not yet',
    next_one: 'Next one',
    up_to_you: 'Up to you',
    plan_the_first_catch_up: 'Plan the first catch-up',
  },
  circlesList: {
    your_circles: 'Your circles',
    sunday_crew: 'Sunday Crew',
    finding_a_time_5_of_6_replied: 'Finding a time · 5 of 6 replied',
    uni_mates: 'Uni mates',
    last_caught_up_2_aug_no_rush: 'Last caught up 2 Aug · No rush',
    book_club: 'Book club',
    locked_in_thu_24_sep: 'Locked in · Thu 24 Sep',
    new_circle: 'New circle',
  },
  components: {
    brand: '{brand}',
    components_and_type_lifted_from_the_design:
      "Components and type, lifted from the design manifesto v1. Terracotta is reserved for the current action and a member's own choices.",
    type: 'Type',
    display_xl_40: 'Display XL 40',
    display_l_31: 'Display L 31',
    date_24_sat_19_sep: 'Date 24 · Sat 19 Sep',
    title_16_figtree_600: 'Title 16 · Figtree 600',
    body_15_figtree_400_line_1_5: 'Body 15 · Figtree 400, line 1.5',
    small_13: 'Small 13',
    label_12_0_07em: 'Label 12 · 0.07em',
    buttons: 'Buttons',
    primary_names_the_outcome: 'Primary · names the outcome',
    secondary: 'Secondary',
    tertiary_quiet_never_hidden: 'Tertiary · quiet, never hidden',
    chip: 'Chip',
    selected: 'Selected',
    marks_and_notices: 'Marks and notices',
    dashed_hasnt_answered: "dashed = hasn't answered",
    advisory_notice_one_sentence: 'Advisory notice, one sentence.',
    warn_confirming_while_someone_hasnt_replied: "Warn: confirming while someone hasn't replied.",
    affirmative_only_never_a_status_colour: 'Affirmative only, never a status colour.',
    availability_track_fill_is_the_affordance_text:
      'Availability track · fill is the affordance, text is the answer',
    thu_17_sep: 'Thu 17 Sep',
    '6_30_10_30_pm': '6:30–10:30 pm',
    '5_30_pm': '5:30 pm',
    '8_pm': '8 pm',
    '10_30_pm': '10:30 pm',
    grey_cells_greyed_by_a_local_calendar:
      'Grey cells: greyed by a local calendar overlay (native only). Always overridable.',
    colour: 'Colour',
    ground: 'ground',
    fbf7f1: '#FBF7F1',
    accent: 'accent',
    c2542f: '#C2542F',
    accent_soft: 'accent-soft',
    f6e5dc: '#F6E5DC',
    support: 'support',
    '4f6b45': '#4F6B45',
    ink: 'ink',
    '221e19': '#221E19',
    ink_2: 'ink-2',
    '6c6156': '#6C6156',
    ink_3: 'ink-3',
    a0958a: '#A0958A',
    invert: 'invert',
    '2e241c': '#2E241C',
  },
  confirmReview: {
    back_to_options: 'Back to options',
    lock_it_in: 'Lock it in?',
    thursday_17_september: 'Thursday 17 September',
    '6_30_8_30_pm': '6:30–8:30 pm',
    '5_of_6_can_make_it_alex': "5 of 6 can make it · Alex hasn't answered",
    where: 'Where',
    hope_st_radio: 'Hope St Radio',
    address_or_map_link_optional: 'Address or map link, optional',
    a_note_for_everyone: 'A note for everyone',
    tables_booked_under_my_name_come_hungry: "Table's booked under my name. Come hungry.",
    alex_hasnt_replied_theyll_see_the_plan:
      "Alex hasn't replied. They'll see the plan and can say whether they're coming.",
    lock_it_in_2: 'Lock it in',
    times_are_frozen_once_locked_later_replies:
      "Times are frozen once locked. Later replies won't move it.",
  },
  confirmedGuest: {
    thursday_17_september: 'Thursday 17 September',
    brunswick_east_open_in_maps: 'Brunswick East · Open in Maps',
    sunday_crew: 'Sunday Crew',
    locked_in: 'Locked in',
    thursday: 'Thursday',
    '17_september': '17 September',
    '6_30_8_30_pm': '6:30–8:30 pm',
    hope_st_radio: 'Hope St Radio',
    brunswick_east: 'Brunswick East ·',
    open_in_maps: 'Open in Maps',
    '5_going_1_to_confirm': '5 going · 1 to confirm',
    maya_priya_tom_jess_sam_alex_to: 'Maya, Priya, Tom, Jess, Sam · Alex to confirm',
    youre_going: "You're going",
    tap_below_if_that_changes: 'Tap below if that changes',
    maya_says_tables_booked_under_my_name:
      "Maya says: “Table's booked under my name. Come hungry.”",
    add_to_calendar: 'Add to calendar',
    i_cant_make_it_after_all: "I can't make it after all",
  },
  confirmedGuestNudge: {
    thursday_17_september: 'Thursday 17 September',
    brunswick_east_open_in_maps: 'Brunswick East · Open in Maps',
    sunday_crew: 'Sunday Crew',
    locked_in: 'Locked in',
    thursday: 'Thursday',
    '17_september': '17 September',
    '6_30_8_30_pm': '6:30–8:30 pm',
    hope_st_radio: 'Hope St Radio',
    brunswick_east: 'Brunswick East ·',
    open_in_maps: 'Open in Maps',
    '5_going_1_to_confirm': '5 going · 1 to confirm',
    maya_priya_tom_jess_sam_alex_to: 'Maya, Priya, Tom, Jess, Sam · Alex to confirm',
    want_a_nudge_on_thursday: 'Want a nudge on Thursday?',
    the_app_sends_one_reminder_two_hours:
      'The app sends one reminder two hours before, and nothing else. Or add it to your calendar below.',
    get_the_app: 'Get the app',
    add_to_calendar: 'Add to calendar',
    i_cant_make_it_after_all: "I can't make it after all",
  },
  confirmedOrg: {
    thursday_17_september: 'Thursday 17 September',
    sunday_crew: 'Sunday Crew',
    locked_in: 'Locked in',
    thursday: 'Thursday',
    '17_september': '17 September',
    '6_30_8_30_pm_hope_st': '6:30–8:30 pm · Hope St Radio',
    ready_to_paste_into_the_group_chat: 'Ready to paste into the group chat',
    locked_in_sunday_crew_thu_17_sep:
      'Locked in: Sunday Crew, Thu 17 Sep, 6:30–8:30 pm at Hope St Radio. Details and add-to-calendar: {domain}/p/8k2v',
    '5_going_1_to_confirm': '5 going · 1 to confirm',
    alex_hasnt_said_yet: "Alex hasn't said yet",
    share_to_group_chat: 'Share to group chat',
    add_to_my_calendar: 'Add to my calendar',
    change_the_time_cancel_this_plan: 'Change the time · Cancel this plan',
  },
  continueAs: {
    welcome_back_which_one_is_you: 'Welcome back. Which one is you?',
    pick_your_name_to_carry_on_where:
      'Pick your name to carry on where you left off. The circle can see when someone rejoins.',
    continue_as: 'Continue as {name}',
    no_names_to_pick: "There's nobody here to continue as. If you're new, start below.",
    signed_in_no_names:
      "You're signed in, so there's nobody to continue as. If you're new to this circle, start below.",
    im_new_here: "I'm new here",
    finding_the_circle: 'Finding the circle',
    rejoining: 'Rejoining',
    reattach_limit:
      "{name} has moved to a new device three times this week, which is the most we allow. Ask the circle's owner to help.",
    saved_place: '{name} saved their place with an account. Sign in with that email to carry on.',
    sign_in: 'Sign in',
    too_many_tries: 'Too many tries from here just now. Wait a few minutes, then try again.',
    couldnt_rejoin: "Something went wrong, so rejoining didn't go through. Please try again.",
    couldnt_load: "We couldn't load this circle just now.",
    youre_offline: "You're offline. Connect, then try again.",
    try_again: 'Try again',
    reference: 'Ref {reference}',
  },
  conversionMap: {
    guest_saved_place_app_when_we_may: 'Guest → saved place → app · when we may ask, and what for',
    two_conversions_each_with_its_own_moments:
      'Two conversions, each with its own moments. A prompt appears only after the thing it would have helped with has just happened. Every prompt is one tap to dismiss, shows at most once per moment per plan, and after two “not now”s stays away for 30 days. Never in an email. Never before an answer.',
    anonymous_guest: 'Anonymous guest',
    answers_from_the_link_this_is_a:
      'Answers from the link. This is a complete, permanent way to use {brand}.',
    saved_place_account_still_web: 'Saved place (account, still web)',
    email_apple_or_google_needed_to_organise:
      'Email, Apple or Google. Needed to organise; otherwise optional.',
    app_installed: 'App installed',
    reminders_on_device_calendar_greying_push_for:
      'Reminders, on-device calendar greying, push for decisions, other circles.',
    link_tapped_from_the_chat: 'Link tapped from the chat',
    join_name_paint_times_send: 'Join → name → paint times → send',
    no_prompts_of_any_kind_before_the: 'No prompts of any kind before the answer',
    installed_members_the_link_opens_in_the: 'Installed members: the link opens in the app',
    universal_link_same_screen_same_identity: 'Universal link; same screen, same identity',
    times_sent: 'Times sent',
    offer_email_updates_for_this_meetup: 'Offer email updates for this meetup',
    sent_screen_not_an_account_not_the: 'Sent screen. Not an account, not the app',
    offer_save_access_on_every_device_as: 'Offer “save access on every device” as a tertiary link',
    only_after_the_email_card_one_tap: 'Only after the email card, one tap to dismiss',
    times_sent_and_email_given: 'Times sent and email given',
    check_your_email_screen_the_response_is: 'Check-your-email screen; the response is already in',
    both_investments_made: 'Both investments made',
    prompt_rather_have_these_on_your_phone: 'Prompt: rather have these on your phone?',
    returned_with_no_session: 'Returned with no session',
    continue_as_name: 'Continue as [name]',
    reattach_in_one_tap_no_sign_in: 'Reattach in one tap, no sign-in',
    prompt_save_your_place: 'Prompt: save your place',
    second_time_it_happens_the_app_sheet: 'Second time it happens: the app sheet instead',
    reattached_twice_the_pain_is_real: 'Reattached twice = the pain is real',
    meetup_locked_in: 'Meetup locked in',
    add_to_calendar_ics_google: 'Add to calendar (.ics / Google)',
    always_available_no_gate: 'Always available, no gate',
    prompt_a_nudge_on_the_day: 'Prompt: a nudge on the day',
    wants_to_start_a_plan_or_quiet: 'Wants to start a plan or quiet ask',
    gate_sign_in_first_organisers_need_a: 'Gate: sign in first (organisers need a stable identity)',
    second_response_in_the_same_circle: 'Second response in the same circle',
    same_flow_no_prompt_on_the_way: 'Same flow, no prompt on the way in',
    prompt_the_app_sheet_once: 'Prompt: the app sheet, once',
    morning_after_tapped_i_was_there: 'Morning after: tapped “I was there”',
    prompt_start_a_circle_for_another_group: 'Prompt: start a circle for another group',
    sign_in_leads_to_web_first_the:
      'Sign-in leads to web first; the app is offered inside, not before',
    signs_in_inside_the_app: 'Signs in inside the app',
    same_email_same_person_circles_appear_links:
      'Same email = same person; circles appear; links open in-app from now on',
    push_asked_only_when_the_first_reminder: 'Push asked only when the first reminder is due',
    what_we_measure: 'What we measure',
    app_nudge_shown_dismissed_tapped_by_moment:
      'app_nudge_shown / dismissed / tapped by moment · account_claimed by moment · app_first_open_linked · share of installed members whose first touch was a guest link · guest → new circle within 30 days',
    what_we_never_do: 'What we never do',
    an_install_wall_an_open_in_app:
      'An install wall. An “open in app” banner on the join or availability screens. A prompt inside an operational email. A second nudge in the same session. Any feature of the core loop held back from the web.',
    why_in_this_order: 'Why in this order',
    the_guest_has_to_experience_a_confirmed:
      "The guest has to experience a confirmed meetup before anything is asked (moat research §6.3). Saving a place is a smaller ask than installing and unlocks organising, so it comes first wherever the person is about to organise. The app is pitched on the four things a browser can't do.",
  },
  createCircle: {
    new_circle: 'New circle',
    whos_this_for: "Who's this for?",
    circle_name: 'Circle name',
    sunday_crew: 'Sunday Crew',
    colour: 'Colour',
    how_often_would_you_like_to_catch: 'How often would you like to catch up?',
    weekly: 'Weekly',
    fortnightly: 'Fortnightly',
    monthly: 'Monthly',
    every_two_months: 'Every two months',
    no_goal: 'No goal',
    a_loose_aim_not_a_rule_well:
      "A loose aim, not a rule. We'll gently nudge someone when it's about time.",
    where_roughly: 'Where, roughly',
    inner_north_optional: 'Inner north, optional',
    create_circle: 'Create circle',
  },
  customWindow: {
    when: 'When?',
    pick_the_dates_to_ask_about: 'Pick the dates to ask about',
    september: 'September',
    mon_14_sun_27_sep: 'Mon 14 – Sun 27 Sep',
    '14_days_the_most_you_can_ask': '14 days · the most you can ask about at once',
    times_of_day: 'Times of day',
    evenings_5_30_10_30: 'Evenings 5:30–10:30',
    weekend_days_9_10_30: 'Weekend days 9–10:30',
    custom: 'Custom',
    use_these_dates: 'Use these dates',
  },
  deadlinePassed: {
    catch_up_next_14_days: 'Catch up · next 14 days',
    '5_of_6_replied': '5 of 6 replied',
    replies_closed: 'Replies closed',
    replies_have_closed_thursday_still_works_for:
      'Replies have closed. Thursday still works for five.',
    nothing_changes_until_you_lock_something_in:
      'Nothing changes until you lock something in. Thursday stays possible until Wednesday night.',
    best_attendance: 'Best attendance',
    '5_of_6': '5 of 6',
    thu_17_sep: 'Thu 17 Sep',
    '6_30_8_30_pm': '6:30–8:30 pm',
    alex_didnt_answer: "Alex didn't answer",
    hand_this_to_someone_else: 'Hand this to someone else',
    another_member_picks_the_time: 'Another member picks the time',
    give_it_one_more_day: 'Give it one more day',
    reopens_replies_until_wed_6_pm: 'Reopens replies until Wed 6 pm',
    lock_in_thursday: 'Lock in Thursday',
  },
  diagnostics: {
    founder_tools: 'Founder tools',
    beta_diagnostics: 'Beta diagnostics',
    allowlisted_accounts_only_aggregates_never_names_or:
      'Allowlisted accounts only. Aggregates, never names or emails.',
    active_circles: 'Active circles',
    plans_confirmed_created: 'Plans confirmed / created',
    reported_happened: 'Reported happened',
    '3_of_4': '3 of 4',
    median_link_reply: 'Median link → reply',
    '1_m_40_s': '1 m 40 s',
    reattached_members: 'Reattached members',
    recent_jobs: 'Recent jobs',
    deadline_reminder_plan_8k2v: 'deadline_reminder · plan 8k2v',
    sent: 'sent',
    outcome_prompt_plan_8k2v: 'outcome_prompt · plan 8k2v',
    queued: 'queued',
    cadence_prompt_circle_s1: 'cadence_prompt · circle s1',
    skipped_active_plan: 'skipped · active plan',
  },
  editPlan: {
    edit_plan: 'Edit plan',
    catch_up: 'Catch up',
    when: 'When?',
    tonight: 'Tonight',
    this_weekend: 'This weekend',
    next_7_days: 'Next 7 days',
    next_14_days: 'Next 14 days',
    custom_21_27_sep: 'Custom · 21–27 Sep',
    how_long: 'How long?',
    '1_hr': '1 hr',
    '1_5_hrs': '1.5 hrs',
    '2_hrs': '2 hrs',
    '3_hrs': '3 hrs',
    at_least_4_of_6_need_to: 'At least 4 of 6 need to make it',
    unchanged: 'Unchanged',
    replies_close_fri_18_sep_6_pm: 'Replies close Fri 18 Sep, 6 pm',
    moved_to_match_the_new_dates: 'Moved to match the new dates',
    changing_the_dates_means_priya_tom_jess:
      'Changing the dates means Priya, Tom, Jess and Sam will be asked for their times again, and Alex gets a fresh ask. Anything sent for the old dates is cleared.',
    save_and_ask_again: 'Save and ask again',
    keep_the_plan_as_it_is: 'Keep the plan as it is',
  },
  emailPrefs: {
    email_preferences: 'Email preferences',
    no_sign_in_needed: 'No sign-in needed. Changes apply straight away.',
    plan: '{circle} · {title}',
    confirmed_time_changes_and_one_reminder: 'Confirmed time, changes and one reminder',
    stopped: 'Off. Ask for updates again from the plan to turn them back on.',
    turning_this_off_stops_emails_for_this:
      "Turning this off stops emails for this meetup only. The plan itself isn't affected.",
    nothing_being_sent: "There's nothing being sent to this address right now.",
    remove_this_email_address_entirely: 'Remove this email address entirely',
    remove_confirm:
      'This stops every email about every meetup to this address, straight away, and this page stops working.',
    remove_it: 'Remove my email address',
    keep_it: 'Keep it',
    removed: 'Your email address is gone.',
    removed_body: "Nothing more will be sent to it, and this page won't open again.",
    link_expired: 'This link has expired.',
    link_expired_body: 'Use the link in the most recent email about the meetup.',
    open_it_again: 'Open the link from your email again.',
    open_it_again_body:
      "The link is cleared from the address bar once it's opened, so a reload can't use it again.",
    loading: 'Finding your email preferences',
    couldnt_load: "We couldn't load your email preferences just now.",
    couldnt_change: "Something went wrong, so that didn't change. Please try again.",
    youre_offline: "You're offline. Connect, then try again.",
    try_again: 'Try again',
    reference: 'Ref {reference}',
  },
  emailVerified: {
    youll_hear_about_this_meetup_by_email: "You'll hear about this meetup by email.",
    youll_hear_about_these_meetups_by_email: "You'll hear about these meetups by email.",
    only_this_one_well_send_the_confirmed:
      "We'll send the confirmed time, any important changes and one reminder. Nothing else.",
    already_confirmed:
      "Its time is already set. We'll send any important changes and one reminder.",
    plan_on: '{circle} · {title}',
    on: 'On',
    every_email_has_a_link_to_stop:
      'Every email has a link to stop these. No account has been created.',
    back_to_circle: 'Back to {circle}',
    save_access_on_every_device: 'Save access on every device',
    verified_nothing_to_send: 'Your email address is verified.',
    nothing_to_send_body:
      "There's nothing to send to it right now: the meetup has finished, or you're no longer in that circle.",
    link_expired: 'This link has expired.',
    link_expired_body:
      'A verification link works once, for 24 hours. Open the plan from your group chat and ask for updates again.',
    open_it_again: 'Open the link from your email again.',
    open_it_again_body:
      "The link is cleared from the address bar once it's opened, so a reload can't use it again.",
    checking: 'Checking the link',
    couldnt_check: "We couldn't check this link just now.",
    youre_offline: "You're offline. Connect, then try again.",
    try_again: 'Try again',
    reference: 'Ref {reference}',
  },
  emails: {
    emails_web_only_members: 'Emails · web-only members',
    operational_only_subjects_never_reveal_a_quiet:
      'Operational only. Subjects never reveal a quiet initiator or calendar details. Every email carries the two links at the bottom.',
    from_brand_to_priya_example_com: 'From {brand} · to priya@example.com',
    turn_on_updates_for_sunday_crews_catch: "Turn on updates for Sunday Crew's catch-up",
    one_tap_works_for_24_hours: 'One tap. Works for 24 hours.',
    tap_below_to_get_the_confirmed_time:
      "Tap below to get the confirmed time, changes and one reminder for this meetup by email. If this wasn't you, ignore it and nothing happens.",
    turn_on_updates: 'Turn on updates',
    this_is_the_only_email_youll_get:
      "This is the only email you'll get unless you tap. No news, no offers.",
    locked_in_sunday_crew_thu_17_sep: 'Locked in: Sunday Crew, Thu 17 Sep',
    '6_30_8_30_pm_at_hope': '6:30–8:30 pm at Hope St Radio',
    thursday_17_september: 'Thursday 17 September',
    '6_30_8_30_pm_hope_st': '6:30–8:30 pm · Hope St Radio, Brunswick East',
    maya_says_tables_booked_under_my_name:
      "Maya says: “Table's booked under my name. Come hungry.”",
    add_to_calendar: 'Add to calendar',
    stop_emails_for_this_meetup: 'Stop emails for this meetup',
    manage_email_preferences: 'Manage email preferences',
    reminder_sunday_crew_tonight_6_30_pm: 'Reminder: Sunday Crew tonight, 6:30 pm',
    hope_st_radio_brunswick_east: 'Hope St Radio, Brunswick East',
    see_you_at_hope_st_radio_at:
      'See you at Hope St Radio at 6:30 pm. 5 going. If plans change, the link below is the place.',
    open_the_plan: 'Open the plan',
  },
  emptyCircle: {
    sunday_crew: 'Sunday Crew',
    just_you_so_far: 'Just you so far',
    invite_link: 'Invite link',
    paste_this_into_the_group_chat_friends:
      'Paste this into the group chat. Friends join and answer from the link. No app needed.',
    domain_join_7f3k: '{domain}/join#…7f3k',
    you_can_start_a_plan_now_too:
      'You can start a plan now, too. Anyone who joins later can still add their times.',
    share_invite_link: 'Share invite link',
    plan_a_catch_up_anyway: 'Plan a catch-up anyway',
  },
  emptyCirclesList: {
    your_circles: 'Your circles',
    a_circle_is_one_group_of_friends:
      'A circle is one group of friends you want to keep seeing. Start with the one whose catch-ups keep slipping.',
    how_it_goes: 'How it goes',
    name_the_circle: 'Name the circle',
    and_share_one_link_into_the_group: 'and share one link into the group chat',
    plan_a_catch_up: 'Plan a catch-up',
    friends_answer_from_the_link_no_app: 'friends answer from the link, no app',
    lock_in_the_best_time: 'Lock in the best time',
    we_give_you_the_message_to_paste: 'we give you the message to paste back',
    create_your_first_circle: 'Create your first circle',
  },
  enterCode: {
    enter_the_code_we_emailed: 'Enter the code we emailed',
    sent_to: 'Sent to {address}. It works for 10 minutes.',
    code: 'Code',
    continue: 'Continue',
    checking: 'Checking',
    wrong_code: "That code didn't work. Check it, or send a new one.",
    send_a_new_code: 'Send a new code',
    new_code_sent: 'A new code is on its way.',
    couldnt_save: "Something went wrong, so your place wasn't saved. Please try again.",
    youre_offline: "You're offline. Connect, then try again.",
    reference: 'Ref {reference}',
  },
  firstCircle: {
    step_1_of_2: 'Step 1 of 2',
    who_do_you_keep_meaning_to_see: 'Who do you keep meaning to see?',
    a_circle_is_one_group_of_friends:
      "A circle is one group of friends. Name it the way you'd say it in the group chat.",
    circle_name: 'Circle name',
    sunday_crew: 'Sunday Crew',
    how_often_would_you_like_to_catch: 'How often would you like to catch up?',
    weekly: 'Weekly',
    fortnightly: 'Fortnightly',
    monthly: 'Monthly',
    every_two_months: 'Every two months',
    no_goal: 'No goal',
    a_loose_aim_not_a_rule_nobody: 'A loose aim, not a rule. Nobody gets scored.',
    create_sunday_crew: 'Create Sunday Crew',
    you_can_change_anything_later: 'You can change anything later.',
  },
  firstPlan: {
    sunday_crew: 'Sunday Crew',
    your_first_catch_up: 'Your first catch-up',
    weve_picked_sensible_defaults_tap_anything_to:
      "We've picked sensible defaults. Tap anything to change it, or just ask the group.",
    catch_up_next_14_days: 'Catch up · next 14 days',
    evenings_and_weekend_days: 'Evenings and weekend days',
    change: 'Change',
    about_2_hours: 'About 2 hours',
    at_least_2_of_3_need_to: 'At least 2 of 3 need to make it',
    adjusts_as_more_people_join: 'Adjusts as more people join',
    replies_close_in_3_days: 'Replies close in 3 days',
    tue_15_sep_6_pm: 'Tue 15 Sep, 6 pm',
    friends_mark_the_times_theyd_actually_be:
      "Friends mark the times they'd actually be up for. You'll see the best options and pick one. Nobody's calendar is shared.",
    ask_the_group: 'Ask the group',
    see_if_people_are_keen_instead: 'See if people are keen instead',
  },
  initiateGate: {
    sunday_crew: 'Sunday Crew',
    save_your_place_first: 'Save your place first',
    planning_a_catch_up_makes_you_the:
      'Planning a catch-up makes you the organiser, so we need to be able to find you again on any device. One sign-in, no app needed.',
    continue_with_apple: 'Continue with Apple',
    continue_with_google: 'Continue with Google',
    continue_with_email: 'Continue with email',
    this_links_your_existing_place_as_priya:
      "This links your existing place as Priya. Nothing you've sent changes.",
    not_now: 'Not now',
  },
  interestPrompt: {
    brand: '{brand}',
    sunday_crew: 'Sunday Crew',
    someone_would_be_up_for_a_catch: 'Someone would be up for a catch-up this weekend. Would you?',
    your_answer_stays_private_unless_enough_people:
      'Your answer stays private unless enough people say yes. Then it opens up to find a time.',
    asked_the_whole_circle: 'Asked the whole circle',
    im_keen: "I'm keen",
    not_this_time: 'Not this time',
    closes_friday_midday_if_it_goes_quiet:
      'Closes Friday midday. If it goes quiet, nobody is told.',
  },
  inviteCircle: {
    step_2_of_2: 'Step 2 of 2',
    now_invite_sunday_crew: 'Now invite Sunday Crew.',
    paste_one_link_into_the_chat_where:
      "Paste one link into the chat where everyone already is. Friends tap it, add a name, and they're in. No app, no account.",
    your_invite_link: 'Your invite link',
    domain_join_7f3k: '{domain}/join#7f3k',
    made_a_sunday_crew_circle_so_we:
      'Made a Sunday Crew circle so we stop losing catch-ups in the chat. Join here, no app needed: {domain}/join#7f3k',
    only_people_with_this_link_can_join:
      "Only people with this link can join. You can reset it any time from the circle's settings.",
    share_to_group_chat: 'Share to group chat',
    copy_link: 'Copy link',
    skip_for_now_ill_plan_first: "Skip for now, I'll plan first",
  },
  joinAsAccount: {
    circle_is_finding_a_time: '{circle} is finding a time to catch up.',
    join_to_pick_your_times:
      "You're not in {circle} yet. Join to pick the times you'd be up for. Everyone in the circle will see that you've joined.",
    join_as: 'Join {circle} as {name}',
    join: 'Join {circle}',
    joining: 'Joining',
    not_now: 'Not now',
    finding_the_circle: 'Finding the circle',
    couldnt_load: "We couldn't load this circle just now.",
    circle_full: '{circle} already has 20 people, which is as many as a circle holds.',
    too_many_tries: 'Too many tries from here just now. Wait a few minutes, then try again.',
    couldnt_join: "Something went wrong, so the join didn't go through. Please try again.",
    youre_offline: "You're offline. Connect, then try again.",
    try_again: 'Try again',
    reference: 'Ref {reference}',
  },
  linkInvalid: {
    brand: '{brand}',
    this_link_isnt_active_any_more: "This link isn't active any more.",
    the_circles_owner_may_have_reset_it:
      "The circle's owner may have reset it. Ask whoever shared it for the current link. Anyone already in the circle still has their place.",
    you_need_the_invite: 'You need the invite link to join.',
    ask_whoever_shared_it:
      "This page is for people already in the circle. Ask whoever shared it for the circle's invite link.",
    open_the_link_again: 'Open the invite link again.',
    open_it_from_the_chat:
      'The page lost track of the invite. Open the link again from the chat it was shared in.',
    this_link_has_expired: 'This link has expired.',
    open_the_plan_from_the_chat:
      'Open the plan from the group chat instead. Your place in the circle is still there.',
    signed_in_as_someone_else: "You're signed in with a different account.",
    this_link_is_for_a_guest_place:
      'This link is for somebody’s place in a circle, and this browser is signed in to another account. Sign out here to use it.',
    sign_out_and_continue: 'Sign out and continue',
    this_link_is_for_an_account: 'This link is for an account.',
    sign_in_with_that_email:
      'Whoever it was sent to has saved their place. Sign in with that email to carry on.',
    sign_in: 'Sign in',
    what_is_brand: 'What is {brand}?',
  },
  main: {
    brand: '{brand}',
    youre_invited: "You're invited",
    circle_is_finding_a_time: '{circle} is finding a time to catch up.',
    inviter_shared_this_link:
      "{inviter} shared this link. Pick the times you'd actually be up for. It takes about a minute, and nobody sees your calendar.",
    someone_shared_this_link:
      "Someone in the circle shared this link. Pick the times you'd actually be up for. It takes about a minute, and nobody sees your calendar.",
    people_in_so_far: '{count} people are in so far',
    one_person_in_so_far: '1 person is in so far',
    no_account_or_app_needed_your_friends:
      'No account or app needed. Your friends only ever see a combined result, never your calendar.',
    choose_my_times: 'Choose my times',
    what_is_brand: 'What is {brand}?',
    opening_the_invite: 'Opening the invite',
    couldnt_open_the_invite: "We couldn't open this invite just now.",
    youre_offline: "You're offline. Connect, then try again.",
    try_again: 'Try again',
    reference: 'Ref {reference}',
  },
  name: {
    what_should_the_group_call_you: 'What should the group call you?',
    just_a_first_name_is_fine_no: 'Just a first name is fine. No email, no password.',
    just_for_this_circle:
      'This is only what {circle} will call you. Your account keeps its own name.',
    your_name: 'Your name',
    priya: 'Priya',
    this_is_what_the_others_will_see:
      'This is what {inviter} and the others will see next to your times.',
    this_is_what_the_circle_will_see: 'This is what the circle will see next to your times.',
    continue: 'Continue',
    joining: 'Joining',
    name_taken:
      'Someone in {circle} is already called {name}. Add something to tell you apart, like “{name} B”.',
    name_unusable: "That name won't work. A first name of up to 40 characters is fine.",
    circle_full: '{circle} already has 20 people, which is as many as a circle holds.',
    too_many_tries: 'Too many tries from here just now. Wait a few minutes, then try again.',
    couldnt_join: "Something went wrong, so the join didn't go through. Please try again.",
    youre_offline: "You're offline. Connect, then try again.",
    reference: 'Ref {reference}',
  },
  noQuorum: {
    drinks_next_7_days: 'Drinks · next 7 days',
    '6_of_6_replied': '6 of 6 replied',
    there_wasnt_enough_overlap_this_time: "There wasn't enough overlap this time.",
    nothing_in_the_next_7_days_works:
      "Nothing in the next 7 days works for at least 4 of you. Here's the closest it got.",
    closest: 'Closest',
    '3_of_6': '3 of 6',
    fri_11_sep: 'Fri 11 Sep',
    '7_9_pm': '7–9 pm',
    not_alex_tom_or_sam: 'Not Alex, Tom or Sam',
    also_three_a_day_later: 'Also three, a day later',
    sat_12_sep: 'Sat 12 Sep',
    '6_30_8_30_pm': '6:30–8:30 pm',
    not_priya_alex_or_sam: 'Not Priya, Alex or Sam',
    what_would_unlock_it: 'What would unlock it',
    lower_to_3_people: 'Lower to 3 people',
    saturday_becomes_possible: 'Saturday becomes possible',
    try_a_wider_window: 'Try a wider window',
    ask_about_the_next_two_weeks_instead: 'Ask about the next two weeks instead',
    close_this_attempt: 'Close this attempt',
    the_circle_just_sees_it_didnt_line: "The circle just sees it didn't line up",
  },
  noneWork: {
    none_of_these_dates_work_for_you: 'None of these dates work for you?',
    thats_useful_to_know_which_is_closer: "That's useful to know. Which is closer to the truth?",
    im_keen_just_not_these_dates: "I'm keen, just not these dates",
    keen_body: "{name} sees you'd like to come. If the window changes, you'll be asked again.",
    keen_body_no_organiser:
      "The group sees you'd like to come. If the window changes, you'll be asked again.",
    not_enough_notice: 'Not enough notice',
    same_as_above_and_well_remember_to:
      "Same as above, and we'll remember to give you more warning next time.",
    not_this_time: 'Not this time',
    no_reason_needed_nobody_is_told_anything:
      'No reason needed. Nobody is told anything beyond that.',
    back_to_my_times: 'Back to my times',
    sending: 'Sending',
  },
  notificationSettings: {
    notifications: 'Notifications',
    sunday_crew: 'Sunday Crew',
    new_plans_options_ready_locked_in_reminders: 'New plans, options ready, locked in, reminders',
    quiet_asks_in_sunday_crew: 'Quiet asks in Sunday Crew',
    someone_wondering_if_people_are_keen: 'Someone wondering if people are keen',
    nudges_to_plan_the_next_one: 'Nudges to plan the next one',
    only_when_its_your_turn: "Only when it's your turn",
    quiet_hours: 'Quiet hours',
    '9_pm_8_am_your_time': '9 pm – 8 am, your time',
    change: 'Change',
    /* eslint-disable circles/copy-voice -- this sentence exists to rule streaks
       out, which is the manifesto's position rather than a lapse from it. */
    we_only_send_when_the_group_needs:
      'We only send when the group needs a decision from you. Never for activity, streaks or news.',
    /* eslint-enable circles/copy-voice */
  },
  offline: {
    your_times_are_saved_on_this_phone: 'Your times are saved on this phone.',
    we_couldnt_reach_brand_just_now_well:
      "We couldn't reach {brand} just now. We'll send them the moment you're back online, and nothing you've painted is lost.",
    saved_at: 'Offline · saved at {time}',
    something_didnt_save: "Something didn't save.",
    please_try_again_organiser:
      'Please try again. If it keeps happening, send {name} this reference and they can pass it on.',
    please_try_again: 'Please try again. If it keeps happening, quote this reference.',
    reference: 'Ref {reference}',
    try_again: 'Try again',
    sending: 'Sending',
  },
  outcome: {
    brand: '{brand}',
    sunday_crew_thu_17_sep: 'Sunday Crew · Thu 17 Sep',
    did_thursdays_catch_up_happen: "Did Thursday's catch-up happen?",
    it_just_sets_when_the_circle_last:
      'It just sets when the circle last got together. Nobody is scored, and nobody is told who came.',
    it_happened: 'It happened',
    it_was_cancelled: 'It was cancelled',
    we_moved_it_outside_brand: 'We moved it outside {brand}',
    not_sure: 'Not sure',
    a_line_for_the_circles_record_optional: "A line for the circle's record, optional",
    great_night_hope_st_again_next_time: 'Great night, Hope St again next time',
    save: 'Save',
  },
  planAnother: {
    plan_another: 'Plan another',
    same_as_last_time: 'Same as last time?',
    filled_in_from_septembers_catch_up_change:
      "Filled in from September's catch-up. Change anything you like.",
    what_are_we_doing: 'What are we doing?',
    catch_up: 'Catch up',
    dinner: 'Dinner',
    drinks: 'Drinks',
    coffee: 'Coffee',
    activity: 'Activity',
    when: 'When?',
    tonight: 'Tonight',
    this_weekend: 'This weekend',
    next_7_days: 'Next 7 days',
    next_14_days: 'Next 14 days',
    custom: 'Custom',
    '2_hours_at_least_4_of_6': '2 hours · at least 4 of 6',
    same_as_last_time_2: 'Same as last time',
    change: 'Change',
    replies_close_in_3_days: 'Replies close in 3 days',
    fri_16_oct_6_pm: 'Fri 16 Oct, 6 pm',
    ask_the_group: 'Ask the group',
    see_if_people_are_keen_instead: 'See if people are keen instead',
  },
  planSetup: {
    plan_openly: 'Plan openly',
    catch_up: 'Catch up',
    what_are_we_doing: 'What are we doing?',
    dinner: 'Dinner',
    drinks: 'Drinks',
    coffee: 'Coffee',
    activity: 'Activity',
    when: 'When?',
    tonight: 'Tonight',
    this_weekend: 'This weekend',
    next_7_days: 'Next 7 days',
    next_14_days: 'Next 14 days',
    custom: 'Custom',
    how_long: 'How long?',
    '1_hr': '1 hr',
    '1_5_hrs': '1.5 hrs',
    '2_hrs': '2 hrs',
    '3_hrs': '3 hrs',
    at_least_4_of_6_need_to: 'At least 4 of 6 need to make it',
    so_one_busy_week_doesnt_sink_the: "So one busy week doesn't sink the whole plan",
    replies_close_in_3_days: 'Replies close in 3 days',
    tue_15_sep_6_pm_you_can: 'Tue 15 Sep, 6 pm · you can pick sooner',
    ask_the_group: 'Ask the group',
    well_give_you_a_short_message_to:
      "We'll give you a short message to paste into the group chat.",
  },
  planShared: {
    brand: '{brand}',
    sunday_crew: 'Sunday Crew',
    now_tell_the_group: 'Now tell the group.',
    paste_this_into_the_chat_where_everyone:
      'Paste this into the chat where everyone already is. People answer from the link.',
    when_can_sunday_crew_actually_catch_up:
      "When can Sunday Crew actually catch up? Mark the times you'd be up for in the next two weeks. Takes a minute, no app needed: {domain}/j/7f3k",
    copy: 'Copy',
    share: 'Share…',
    replies_close_tue_15_sep_6_pm:
      "Replies close Tue 15 Sep, 6 pm. We'll show you the best options as they come in.",
    done: 'Done',
  },
  privacy: {
    privacy: 'Privacy',
    what_we_keep_and_who_sees_it: 'What we keep, and who sees it',
    your_calendar_stays_on_your_phone: 'Your calendar stays on your phone',
    if_you_turn_on_the_calendar_check:
      'If you turn on the calendar check, we read busy times on this device only, to grey out clashes. Event names never leave your phone.',
    friends_see_a_combined_result: 'Friends see a combined result',
    they_see_which_options_work_for_you:
      "They see which options work for you, never a personal schedule. Before enough people are keen on a quiet ask, nobody sees anyone's answer.",
    email_is_optional_and_narrow: 'Email is optional and narrow',
    meetup_updates_only_per_meetup_with_a:
      'Meetup updates only, per meetup, with a stop link in every email. We never sell or share addresses.',
    you_can_leave_a_circle_delete_your:
      'You can leave a circle, delete your data or export it any time from Account.',
  },
  pushAsk: {
    want_to_know_when_sunday_crew_has: 'Want to know when Sunday Crew has options?',
    wed_send_one_notification_when_options_are:
      "We'd send one notification when options are ready, one when a time is locked in, and one reminder before. Nothing about activity.",
    options_ready: 'Options ready',
    locked_in_changed_or_off: 'Locked in, changed or off',
    one_reminder_2_hours_before: 'One reminder, 2 hours before',
    anything_else: 'Anything else',
    never: 'Never',
    turn_on_notifications: 'Turn on notifications',
    not_now: 'Not now',
  },
  pushes: {
    push_notifications_app_members: 'Push notifications · app members',
    every_one_deep_links_to_a_decision:
      'Every one deep-links to a decision. At most one deadline reminder per person per plan. Quiet hours 9 pm – 8 am local. Nothing names a quiet initiator.',
    new_plan_to_members: 'New plan · to members',
    sunday_crew_when_can_you_catch_up:
      'Sunday Crew: when can you catch up in the next two weeks? Takes a minute.',
    on_create: 'on create',
    quiet_ask_to_members_except_initiator: 'Quiet ask · to members except initiator',
    someone_in_sunday_crew_would_be_up:
      'Someone in Sunday Crew would be up for a catch-up this weekend. Would you?',
    threshold_reached_to_initiator: 'Threshold reached · to initiator',
    enough_people_are_keen_do_you_want: 'Enough people are keen. Do you want to pick the time?',
    at_threshold: 'at threshold',
    threshold_reached_to_keen_members: 'Threshold reached · to keen members',
    sunday_crew_enough_people_are_keen_for:
      'Sunday Crew: enough people are keen for this weekend. Choose your times.',
    deadline_approaching_to_non_responders_only: 'Deadline approaching · to non-responders only',
    sunday_crew_closes_replies_tomorrow_at_6:
      'Sunday Crew closes replies tomorrow at 6 pm. Still keen?',
    '24_h_before': '24 h before',
    options_ready_to_organiser: 'Options ready · to organiser',
    thursday_looks_good_for_five_of_you: 'Thursday looks good for five of you. Have a look.',
    on_quorum: 'on quorum',
    locked_in_to_members: 'Locked in · to members',
    locked_in_sunday_crew_thu_17_sep:
      'Locked in: Sunday Crew, Thu 17 Sep, 6:30 pm at Hope St Radio.',
    on_confirm: 'on confirm',
    changed_off_to_members: 'Changed / off · to members',
    change_of_plan_thursdays_catch_up_is:
      "Change of plan: Thursday's catch-up is off. Maya is asking for new times.",
    on_change: 'on change',
    reminder_to_going: 'Reminder · to going',
    sunday_crew_tonight_6_30_pm_at: 'Sunday Crew tonight, 6:30 pm at Hope St Radio.',
    '2_h_before': '2 h before',
    did_it_happen_to_organiser: 'Did it happen? · to organiser',
    did_thursdays_catch_up_happen_one_tap: "Did Thursday's catch-up happen? One tap.",
    next_morning: 'next morning',
    about_time_to_one_person_only: 'About time · to one person only',
    its_been_about_a_month_since_sunday:
      "It's been about a month since Sunday Crew got together. Your turn to plan, if you're keen. No rush.",
    cadence_due: 'cadence due',
  },
  reattachedNudge: {
    sunday_crew: 'Sunday Crew',
    welcome_back_priya: 'Welcome back, Priya.',
    youve_rejoined_from_a_new_browser_and:
      "You've rejoined from a new browser and your times are still here. Maya can see you rejoined.",
    keep_your_place_for_good: 'Keep your place for good?',
    sign_in_once_with_your_email_apple:
      "Sign in once with your email, Apple or Google and you'll never have to pick your name from a list again. Still no app needed.",
    save_my_place: 'Save my place',
    not_now: 'Not now',
    carry_on_to_sunday_crew: 'Carry on to Sunday Crew',
  },
  rescheduledGuest: {
    sunday_crew: 'Sunday Crew',
    brand: '{brand}',
    change_of_plan: 'Change of plan',
    thursday_is_off_the_table_new_times: 'Thursday is off the table. New times?',
    maya_reopened_the_plan_for_the_week:
      "Maya reopened the plan for the week after. Your earlier times don't carry over, so it's a fresh ask.",
    previously: 'Previously',
    thu_17_sep_6_30_8_30: 'Thu 17 Sep, 6:30–8:30 pm',
    now_asking_about: 'Now asking about',
    mon_21_sun_27_sep: 'Mon 21 – Sun 27 Sep',
    choose_my_times: 'Choose my times',
    not_this_time: 'Not this time',
  },
  saveAccess: {
    keep_your_place_on_every_device: 'Keep your place on every device',
    sign_in_with_your_email:
      "Sign in with your email and you'll never have to rejoin {circle} from a new phone or browser. It's optional.",
    your_email: 'Your email',
    you_example_com: 'you@example.com',
    well_send_a_one_time_code_this:
      "We'll send a one-time code. This is an account, so it's separate from meetup emails. It doesn't subscribe you to anything.",
    not_an_address: "That doesn't look like an email address.",
    send_me_a_code: 'Send me a code',
    sending: 'Sending',
    not_now: 'Not now',
    already_saved: 'Your place is already saved.',
    already_saved_body: "You're signed in, so you can get back to {circle} from any device.",
    back: 'Back',
    couldnt_send: "Something went wrong, so the code didn't go. Please try again.",
    too_many_tries: 'Too many codes asked for just now. Wait a few minutes, then try again.',
    youre_offline: "You're offline. Connect, then try again.",
  },
  secondSent: {
    prefer_email_turn_on_updates_for_this: 'Prefer email? Turn on updates for this meetup .',
    brand: '{brand}',
    sunday_crew: 'Sunday Crew',
    thanks_priya_your_times_are_in: 'Thanks, Priya. Your times are in.',
    thats_the_second_time_round_maya_will:
      "That's the second time round. Maya will pick once replies close on Friday.",
    doing_this_again_next_month: 'Doing this again next month?',
    the_app_greys_out_your_clashes_while:
      'The app greys out your clashes while you paint, reminds you before, and pings you only when a decision needs you. Nothing else changes.',
    get_the_app: 'Get the app',
    not_now: 'Not now',
    prefer_email: 'Prefer email?',
    turn_on_updates_for_this_meetup: 'Turn on updates for this meetup',
  },
  sent: {
    thanks_times_in: 'Thanks, {name}. Your times are in.',
    thanks_answer_in: 'Thanks, {name}. Your answer is in.',
    thanks_times_in_anonymous: 'Thanks. Your times are in.',
    thanks_answer_in_anonymous: 'Thanks. Your answer is in.',
    organiser_picks:
      '{name} will pick a time once replies close on {day}. The plan will land in the group chat.',
    time_gets_picked:
      'A time gets picked once replies close on {day}. The plan will land in the group chat.',
    get_updates_about_this_meetup_by_email: 'Get updates about this meetup by email',
    well_send_the_confirmed_time_any_important:
      "We'll send the confirmed time, any important changes and one reminder. Verify your email to turn this on. Nothing else.",
    your_email: 'Your email',
    you_example_com: 'you@example.com',
    not_an_address: "That doesn't look like an email address.",
    send_verification_email: 'Send verification email',
    sending: 'Sending',
    not_now: 'Not now',
    too_many_tries: "That's as many links as we send to one address in a day. Try again tomorrow.",
    youre_offline: "You're offline. Connect, then try again.",
    couldnt_send: "Something went wrong, so the link didn't go. Please try again.",
    reference: 'Ref {reference}',
    save_access_note: 'Optional: save your access on every device, so you never have to rejoin.',
    save_access: 'Save access on every device',
    place_saved: 'Your place is saved. Sign in with {address} on any device to get back to it.',
    finding_it: 'Finding your answer',
    couldnt_load: "We couldn't load this just now.",
    try_again: 'Try again',
    see_my_answer: 'Change my answer',
  },
  settings: {
    sunday_crew: 'Sunday Crew',
    circle_settings: 'Circle settings',
    invite_link: 'Invite link',
    domain_join_7f3k: '{domain}/join#…7f3k',
    copy_link: 'Copy link',
    reset_link: 'Reset link',
    resetting_the_link_doesnt_affect_anyone_whos:
      "Resetting the link doesn't affect anyone who's already in.",
    catch_up: 'Catch up',
    about_monthly: 'About monthly',
    change: 'Change',
    who_gets_nudged_to_plan_the_next: 'Who gets nudged to plan the next one',
    take_turns: 'Take turns',
    quiet_asks: 'Quiet asks',
    on: 'On',
    members: 'Members',
    maya: 'Maya',
    you_owner: 'You · owner',
    priya: 'Priya',
    joined_3_sep: 'Joined 3 Sep',
    remove: 'Remove',
    alex: 'Alex',
    tom: 'Tom',
    joined_4_sep: 'Joined 4 Sep',
    jess: 'Jess',
    sam: 'Sam',
    joined_5_sep: 'Joined 5 Sep',
    archive_this_circle: 'Archive this circle',
  },
  shareMessages: {
    share_sheet_messages_pasted_into_the_group: 'Share-sheet messages · pasted into the group chat',
    generated_per_state_the_organiser_never_composes:
      'Generated per state. The organiser never composes. The invite secret rides in the URL fragment, so chat link previews never see it.',
    invite_to_circle: 'Invite to circle',
    made_a_sunday_crew_circle_so_we:
      'Made a Sunday Crew circle so we stop losing catch-ups in the chat. Join here, no app needed: {domain}/join#7f3k',
    new_plan: 'New plan',
    when_can_sunday_crew_actually_catch_up:
      "When can Sunday Crew actually catch up? Mark the times you'd be up for in the next two weeks. Takes a minute: {domain}/j/7f3k",
    waiting: 'Waiting',
    were_waiting_on_4_replies_before_picking:
      "We're waiting on 4 replies before picking a time: {domain}/j/7f3k",
    locked_in: 'Locked in',
    locked_in_sunday_crew_thu_17_sep:
      'Locked in: Sunday Crew, Thu 17 Sep, 6:30–8:30 pm at Hope St Radio. Details and add-to-calendar: {domain}/p/8k2v',
    changed: 'Changed',
    change_of_plan_thursday_is_off_new:
      'Change of plan: Thursday is off. New times for the week after, please: {domain}/j/7f3k',
    cancelled: 'Cancelled',
    update_thursdays_sunday_crew_catch_up_is:
      "Update: Thursday's Sunday Crew catch-up is off. Sorry all, will try again in October. {domain}/p/8k2v",
    link_preview_what_the_chat_shows: 'Link preview · what the chat shows',
    sunday_crew_is_finding_a_time_to: 'Sunday Crew is finding a time to catch up',
    pick_the_times_youd_actually_be_up:
      "Pick the times you'd actually be up for. No app needed. · {domain}",
    circle_name_only_never_member_names_dates:
      'Circle name only. Never member names, dates chosen, or anything from a quiet ask.',
  },
  signIn: {
    brand: '{brand}',
    make_room_for_each_other: 'Make room for each other.',
    find_a_time_your_friends_are_actually:
      'Find a time your friends are actually up for, without chasing everyone or sharing calendars.',
    your_email: 'Your email',
    maya_example_com: 'maya@example.com',
    well_email_a_one_time_code_no:
      "We'll email a one-time code. No password. Friends you invite never need an account.",
    send_me_a_code: 'Send me a code',
  },
  sparkExpired: {
    brand: '{brand}',
    sunday_crew: 'Sunday Crew',
    not_enough_people_were_free_this_time: 'Not enough people were free this time.',
    this_one_closed_quietly_nobody_else_knows:
      'This one closed quietly. Nobody else knows you asked, and nobody is told who said what.',
    weekends_have_been_tight_for_a_few:
      'Weekends have been tight for a few people lately. A wider window sometimes helps.',
    try_again_another_time: 'Try again another time',
    back_to_sunday_crew: 'Back to Sunday Crew',
  },
  sparkOpenedMember: {
    brand: '{brand}',
    sunday_crew_started_quietly: 'Sunday Crew · started quietly',
    enough_people_are_keen_for_this_weekend: 'Enough people are keen for this weekend.',
    tom_volunteered_to_pick_the_time_mark:
      "Tom volunteered to pick the time. Mark the times you'd actually be up for, even if you said “not this time” earlier.",
    '3_of_6_keen_so_far_replies': '3 of 6 keen so far · Replies close Fri 11 Sep, 6 pm',
    this_plan_started_quietly_we_dont_say: "This plan started quietly. We don't say who asked.",
    choose_my_times: 'Choose my times',
    not_this_one: 'Not this one',
  },
  sparkSetup: {
    see_if_people_are_keen: 'See if people are keen',
    ask_quietly: 'Ask quietly',
    nobody_sees_who_asked_if_three_people:
      'Nobody sees who asked. If three people are keen, it opens up to find a time. If not, it closes and nobody knows.',
    for_when: 'For when?',
    tonight: 'Tonight',
    this_weekend: 'This weekend',
    next_7_days: 'Next 7 days',
    next_14_days: 'Next 14 days',
    to_do_what: 'To do what?',
    anything: 'Anything',
    dinner: 'Dinner',
    drinks: 'Drinks',
    coffee: 'Coffee',
    activity: 'Activity',
    stop_asking: 'Stop asking',
    tonight_9_pm: 'Tonight, 9 pm',
    friday_midday: 'Friday midday',
    when_the_weekend_starts: 'When the weekend starts',
    in_a_group_this_size_people_can:
      'In a group this size people can sometimes guess. We never confirm it, in the app or in any message.',
  },
  sparkWaiting: {
    sunday_crew: 'Sunday Crew',
    brand: '{brand}',
    asked_quietly: 'Asked quietly',
    were_checking_whos_keen_for_this_weekend: "We're checking who's keen for this weekend.",
    well_tell_you_if_enough_people_say:
      "We'll tell you if enough people say yes. Until then nobody, including you, sees who answered.",
    closes: 'Closes',
    fri_11_sep_12_pm: 'Fri 11 Sep, 12 pm',
    opens_up_when: 'Opens up when',
    '3_of_6_are_keen': '3 of 6 are keen',
    changed_your_mind_you_can_withdraw_it:
      'Changed your mind? You can withdraw it and nobody will know it was asked.',
    back_to_sunday_crew: 'Back to Sunday Crew',
    withdraw_the_ask: 'Withdraw the ask',
  },
  thresholdRole: {
    brand: '{brand}',
    sunday_crew: 'Sunday Crew',
    enough_people_are_keen: 'Enough people are keen.',
    three_of_you_want_to_catch_up:
      'Three of you want to catch up this weekend. Someone needs to pick the time. That can be you, or you can ask for a volunteer.',
    ill_organise: "I'll organise",
    your_name_will_show_as_the_organiser:
      "Your name will show as the organiser. We still won't say who asked first.",
    ask_for_a_volunteer: 'Ask for a volunteer',
    everyone_whos_keen_sees_a_one_tap:
      "Everyone who's keen sees a one-tap “I'll pick the time”. Your name stays out of it.",
    if_nobody_volunteers_before_replies_close_the:
      'If nobody volunteers before replies close, the circle owner gets a quiet nudge.',
  },
  volunteer: {
    sunday_crew: 'Sunday Crew',
    started_quietly: 'Started quietly',
    three_people_are_keen_for_this_weekend: 'Three people are keen for this weekend.',
    someone_needs_to_pick_the_time_it:
      "Someone needs to pick the time. It takes about a minute once everyone's sent their times.",
    '3_of_6_are_keen_so_far': "3 of 6 are keen so far · others can still join. We don't show who.",
    this_plan_started_quietly_we_dont_say:
      "This plan started quietly. We don't say who asked, and we never will.",
    ill_pick_the_time: "I'll pick the time",
    send_my_times: 'Send my times',
    not_this_one: 'Not this one',
  },
  waiting: {
    catch_up_next_14_days: 'Catch up · next 14 days',
    '2_of_6_replied': '2 of 6 replied',
    closes_tue_6_pm: 'Closes Tue 6 pm',
    waiting_on_a_few_more: 'Waiting on a few more.',
    options_appear_once_at_least_4_people:
      "Options appear once at least 4 people can make the same time. No need to chase anyone yet; a reminder goes to anyone who hasn't answered on Monday.",
    so_far: 'So far',
    thu_17_sep: 'Thu 17 Sep',
    '6_30_10_30_pm_works_for': '6:30–10:30 pm works for 2',
    '5_30_pm': '5:30 pm',
    '8_pm': '8 pm',
    '10_30_pm': '10:30 pm',
    only_you_see_this_while_its_incomplete:
      "Only you see this while it's incomplete. Members see the options once there are some.",
    share_the_link_again: 'Share the link again',
    edit_the_plan: 'Edit the plan',
  },
  wasThere: {
    brand: '{brand}',
    sunday_crew_thu_17_sep: 'Sunday Crew · Thu 17 Sep',
    did_you_make_it_to_thursdays_catch: "Did you make it to Thursday's catch-up?",
    helps_the_group_keep_a_light_record:
      'Helps the group keep a light record of when you last got together. Nobody keeps score.',
    i_was_there: 'I was there',
    i_couldnt_make_it: "I couldn't make it",
    not_now: 'Not now',
  },
  welcome: {
    brand: '{brand}',
    make_room_for_each_other: 'Make room for each other.',
    find_a_time_your_friends_are_actually:
      'Find a time your friends are actually up for, without chasing everyone or sharing calendars.',
    continue_with_apple: 'Continue with Apple',
    continue_with_google: 'Continue with Google',
    continue_with_email: 'Continue with email',
    friends_you_invite_never_need_an_account:
      'Friends you invite never need an account. By continuing you agree to the',
    terms: 'terms',
    and: 'and',
    privacy: 'privacy',
    basics_no_ads_no_selling_data_18: 'basics: no ads, no selling data, 18+.',
  },
  yourName: {
    what_should_friends_call_you: 'What should friends call you?',
    filled_in_from_your_google_account_change:
      'Filled in from your Google account. Change it if you like.',
    your_name: 'Your name',
    maya: 'Maya',
    time_zone: 'Time zone',
    melbourne_aest_from_your_phone: 'Melbourne (AEST) · from your phone',
    change: 'Change',
    thats_all_we_need_no_photo_no: "That's all we need. No photo, no phone number, no contacts.",
    continue: 'Continue',
  },
} as const;

export type Copy = typeof en;
export type Screen = keyof Copy;
