import js from '@eslint/js';
import boundaries from 'eslint-plugin-boundaries';
import globals from 'globals';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';

import circles from './tooling/eslint-rules/index.mjs';
import tseslint from 'typescript-eslint';

/**
 * Architecture §7.2 is enforced here, in two halves:
 *
 *   `boundaries/element-types` — which *folders* may import which, by path.
 *     Notably, inside `apps/app`, `data` and `platform` never import `features`.
 *   `boundaries/external`      — which *packages* each layer may import.
 *     Notably, `packages/domain` may import nothing but `date-fns-tz`; a stray
 *     `import 'react'` there is a lint error, not a review comment.
 *
 * `apps/app` (S0-02) and `supabase/functions` (S0-06) do not exist yet; their
 * elements are declared now so those tickets inherit the rule rather than write it.
 */
const elements = [
  // Tests first: `boundaries` takes the first pattern that matches, and a test
  // is allowed the test libraries that the package it tests is not.
  { type: 'package-test', pattern: 'packages/*/src/**/*.test.ts', mode: 'full' },
  // And the app's own integration tests, for the same reason one layer along:
  // they drive the real stack, so they reach for things the layer they sit in
  // must never have — `node:child_process` to ask Postgres a question the
  // client deliberately cannot ask, because PostgREST exposes only `public`.
  // Narrow on purpose: `*.integration.test.ts`, not every test, so an ordinary
  // unit test under `data/` keeps the layer's restrictions — and
  // `*.integration.ts` for what those suites share (`data/testing/`), which
  // nothing but an integration test may import.
  {
    type: 'app-integration-test',
    pattern: ['apps/*/src/**/*.integration.test.ts', 'apps/*/src/**/*.integration.ts'],
    mode: 'full',
  },
  { type: 'domain', pattern: 'packages/domain/**/*', mode: 'full' },
  { type: 'contracts', pattern: 'packages/contracts/**/*', mode: 'full' },
  { type: 'tokens', pattern: 'packages/tokens/**/*', mode: 'full' },
  { type: 'config', pattern: 'packages/config/**/*', mode: 'full' },
  { type: 'app-routes', pattern: 'apps/app/app/**/*', mode: 'full' },
  { type: 'app-features', pattern: 'apps/app/src/features/**/*', mode: 'full' },
  { type: 'app-components', pattern: 'apps/app/src/components/**/*', mode: 'full' },
  { type: 'app-data', pattern: 'apps/app/src/data/**/*', mode: 'full' },
  { type: 'app-platform', pattern: 'apps/app/src/platform/**/*', mode: 'full' },
  { type: 'app-copy', pattern: 'apps/app/src/copy/**/*', mode: 'full' },
  { type: 'app-analytics', pattern: 'apps/app/src/analytics/**/*', mode: 'full' },
  { type: 'functions', pattern: 'supabase/functions/**/*', mode: 'full' },
];

const appLayers = [
  'app-features',
  'app-components',
  'app-data',
  'app-platform',
  'app-copy',
  'app-analytics',
];

const sharedPackages = ['contracts', 'domain', 'tokens', 'config'];

const appExternals = [
  '@circles/*',
  'react',
  'react-dom',
  'react-native',
  'react-native-*',
  '@react-native/*',
  'expo',
  'expo-*',
  '@expo/*',
  '@supabase/*',
  '@tanstack/*',
  'zod',
  'date-fns',
  'date-fns-tz',
  'vitest',
  '@testing-library/*',
];

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'docs/**',
      '.claude/**',
      // Generated by `expo prebuild`, git-ignored, never edited by hand.
      'apps/*/android/**',
      'apps/*/ios/**',
      '**/.expo/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,mts,cts,js,mjs,cjs}'],
    plugins: { boundaries },
    settings: {
      // Source only. Build and tooling configs are not part of the architecture.
      'boundaries/include': [
        'apps/*/app/**/*',
        'apps/*/src/**/*',
        'packages/*/src/**/*',
        'supabase/functions/*/**/*',
      ],
      'boundaries/elements': elements,
    },
    rules: {
      'boundaries/element-types': [
        'error',
        {
          default: 'disallow',
          message: '${file.type} is not allowed to import ${dependency.type} (architecture §7.2)',
          rules: [
            { from: ['domain'], allow: ['domain'] },
            // A test may reach into any package's source; that is what it is for.
            { from: ['package-test'], allow: ['domain', 'contracts', 'tokens', 'config'] },
            {
              from: ['app-integration-test'],
              allow: [...appLayers, 'contracts', 'domain', 'tokens', 'config'],
            },
            { from: ['contracts'], allow: ['contracts', 'domain'] },
            { from: ['tokens'], allow: ['tokens'] },
            { from: ['config'], allow: ['config'] },
            {
              from: ['app-routes'],
              allow: ['app-routes', 'app-features', ...appLayers, ...sharedPackages],
            },
            { from: ['app-features'], allow: [...appLayers, ...sharedPackages] },
            {
              from: ['app-components'],
              allow: ['app-components', 'app-copy', 'tokens', 'domain', 'contracts'],
            },
            // `data` and `platform` never import `features`.
            {
              from: ['app-data', 'app-platform'],
              allow: ['app-data', 'app-platform', 'contracts', 'domain', 'config'],
            },
            { from: ['app-copy'], allow: ['app-copy'] },
            {
              from: ['app-analytics'],
              allow: ['app-analytics', 'app-data', 'contracts', 'domain', 'config'],
            },
            { from: ['functions'], allow: ['functions', 'contracts', 'domain', 'config'] },
          ],
        },
      ],
      'boundaries/external': [
        'error',
        {
          default: 'disallow',
          message:
            '${file.type} is not allowed to import "${dependency.source}" (architecture §7.2)',
          rules: [
            // The domain stays pure: no React, no Supabase, no Deno, no I/O.
            // `date-fns-tz` and nothing else — and `shared/zone.ts` is the only
            // file even that may reach, which `no-restricted-imports` enforces
            // below. The test libraries are deliberately absent: a `vitest`
            // import in `engine.ts` would compile and then fail on Deno, where
            // there is no `node_modules` to find it in.
            { from: ['domain'], allow: ['date-fns-tz'] },
            { from: ['contracts'], allow: ['@circles/domain', 'zod'] },
            { from: ['tokens'], allow: [] },
            { from: ['config'], allow: ['zod'] },
            // Test-only, and only in a test: `tsconfig` keeps `*.test.ts` out of
            // `dist`, so none of these can reach an Edge Function.
            {
              from: ['package-test'],
              allow: ['@circles/*', 'date-fns-tz', 'zod', 'vitest', 'fast-check', 'ical.js'],
            },
            {
              from: ['app-integration-test'],
              allow: [...appExternals, 'node:child_process', 'node:path'],
            },
            { from: ['app-routes', ...appLayers], allow: appExternals },
            {
              // `@supabase/*` is the client an Edge Function reaches the database
              // with — the service-role one in §7.4's step 4, and the
              // caller-scoped one that makes `auth.uid()` mean the caller. It is
              // allowed here and nowhere else: the domain importing it is the
              // thing the dependency rule exists to stop.
              from: ['functions'],
              allow: [
                '@circles/*',
                '@supabase/*',
                'zod',
                'vitest',
                'resend',
                'date-fns-tz',
                // React Email (ADR 0008): the email templates are components,
                // rendered to HTML inside the function that sends them.
                'react',
                'react/*',
                '@react-email/*',
                'npm:*',
                'jsr:*',
              ],
            },
          ],
        },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // A combining mark written as `\u0301` is somebody saying what they mean;
      // one pasted in as a literal character, invisibly attached to the one
      // before it, is the accident this rule exists to catch. Escapes are
      // allowed so that a character class *of* combining marks — the
      // display-name comparator has one, and it has to match a class in SQL —
      // can be written plainly.
      'no-misleading-character-class': ['error', { allowEscape: true }],
    },
  },
  {
    // The Rules of Hooks are correctness for a React app, and the dependency
    // rule catches exactly the kind of stale-closure bug the availability
    // painter is prone to.
    files: ['apps/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  {
    // Zone conversion is confined to one file (architecture §7.3). Everything
    // else in the domain works in `Instant` or `LocalDate` + minutes, so a
    // conversion cannot quietly appear in the middle of the candidate engine —
    // which is exactly where a daylight-saving bug would be hardest to see.
    files: ['packages/domain/src/**/*.ts'],
    ignores: ['packages/domain/src/shared/zone.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'date-fns-tz',
              message:
                'Only shared/zone.ts may convert between zones. Use toLocal/fromLocal from there.',
            },
          ],
        },
      ],
    },
  },
  {
    // Copy is the only place user-facing strings live, so it is the only place
    // the voice can be checked (design manifesto §4).
    files: ['apps/*/src/copy/**/*.ts'],
    plugins: { circles },
    rules: { 'circles/copy-voice': 'error' },
  },
  {
    // Screens and components compose copy; they never contain it. Tests are
    // exempt: a test's strings are its fixtures, and routing them through the
    // copy file would only make the test harder to read.
    files: ['apps/*/src/features/**/*.tsx', 'apps/*/src/components/**/*.tsx'],
    ignores: ['**/*.test.tsx'],
    plugins: { circles },
    rules: { 'circles/no-literal-jsx-strings': 'error' },
  },
  {
    // Repository tooling: Node scripts and build configs, outside the layers.
    files: ['scripts/**/*.{js,mjs,ts}', 'eslint.config.mjs', '**/*.config.{ts,mjs}'],
    languageOptions: {
      globals: globals.node,
    },
  },
  prettier,
);
