/**
 * `@circles/tokens` — design tokens generated from `docs/design/gen.py`, plus
 * the bundled fonts (ADR 0002). Generated by `pnpm gen:tokens`; the generator
 * and the token set land in S0-03.
 */
export const PACKAGE_NAME = '@circles/tokens';
